/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PersonManager;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author jiaye
 */
public class CreatePersonJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    PersonDirectory personDirectory;
    /**
     * Creates new form CreatePersonJPanel
     */
    public CreatePersonJPanel(JPanel container, PersonDirectory directory) {
        initComponents();
        
        userProcessContainer = container;
        personDirectory = directory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblFirstname = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        lblLastname = new javax.swing.JLabel();
        txt_lastname = new javax.swing.JTextField();
        lblSsn = new javax.swing.JLabel();
        txt_ssn = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txt_age = new javax.swing.JTextField();
        home_addr = new javax.swing.JPanel();
        lbl_homeaddr = new javax.swing.JLabel();
        lblH_streetaddr = new javax.swing.JLabel();
        txt_h_streetaddr = new javax.swing.JTextField();
        lblH_unit = new javax.swing.JLabel();
        txt_h_unit = new javax.swing.JTextField();
        lblH_city = new javax.swing.JLabel();
        txt_h_city = new javax.swing.JTextField();
        lblH_state = new javax.swing.JLabel();
        txt_h_state = new javax.swing.JTextField();
        lblH_zip = new javax.swing.JLabel();
        txt_h_zip = new javax.swing.JTextField();
        lblH_phone = new javax.swing.JLabel();
        txt_h_phone = new javax.swing.JTextField();
        work_addr = new javax.swing.JPanel();
        lbl_workaddr = new javax.swing.JLabel();
        lblW_streetaddr = new javax.swing.JLabel();
        txt_w_streetaddr = new javax.swing.JTextField();
        lblW_unit = new javax.swing.JLabel();
        txt_w_unit = new javax.swing.JTextField();
        lblW_city = new javax.swing.JLabel();
        txt_w_city = new javax.swing.JTextField();
        lblW_state = new javax.swing.JLabel();
        txt_w_state = new javax.swing.JTextField();
        lblW_zip = new javax.swing.JLabel();
        txt_w_zip = new javax.swing.JTextField();
        lblW_phone = new javax.swing.JLabel();
        txt_w_phone = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        lblShoesnum = new javax.swing.JLabel();
        txt_shoesnum = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 186, 157));

        btnBack.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Person Profile");

        lblFirstname.setText("First Name");

        txt_firstname.setAutoscrolls(false);

        lblLastname.setText("Last Name");

        txt_lastname.setAutoscrolls(false);

        lblSsn.setText("Social Security Number");

        txt_ssn.setAutoscrolls(false);

        lblAge.setText("Age");

        txt_age.setAutoscrolls(false);

        home_addr.setBackground(new java.awt.Color(255, 204, 204));

        lbl_homeaddr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_homeaddr.setText("Home Address");

        lblH_streetaddr.setText("Street Address");

        lblH_unit.setText("Unit Number");

        lblH_city.setText("City");

        lblH_state.setText("State");

        lblH_zip.setText("Zip Code");

        lblH_phone.setText("Phone Number");

        javax.swing.GroupLayout home_addrLayout = new javax.swing.GroupLayout(home_addr);
        home_addr.setLayout(home_addrLayout);
        home_addrLayout.setHorizontalGroup(
            home_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_addrLayout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addGroup(home_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_h_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_h_state, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_h_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblH_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblH_state, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblH_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(home_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(home_addrLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(home_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblH_zip, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_h_city, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_h_zip, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_homeaddr)
                        .addComponent(lblH_streetaddr, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblH_city, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_h_streetaddr, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(206, Short.MAX_VALUE)))
        );
        home_addrLayout.setVerticalGroup(
            home_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_addrLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblH_unit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_h_unit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblH_state)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_h_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblH_phone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_h_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(home_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(home_addrLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbl_homeaddr)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(lblH_streetaddr)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txt_h_streetaddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(lblH_city)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txt_h_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(11, 11, 11)
                    .addComponent(lblH_zip)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txt_h_zip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );

        work_addr.setBackground(new java.awt.Color(255, 204, 153));

        lbl_workaddr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_workaddr.setText("Work Address");

        lblW_streetaddr.setText("Street Address");

        lblW_unit.setText("Unit Number");

        lblW_city.setText("City");

        lblW_state.setText("State");

        lblW_zip.setText("Zip Code");

        lblW_phone.setText("Phone Number");

        javax.swing.GroupLayout work_addrLayout = new javax.swing.GroupLayout(work_addr);
        work_addr.setLayout(work_addrLayout);
        work_addrLayout.setHorizontalGroup(
            work_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, work_addrLayout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addGroup(work_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_w_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_w_state, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_w_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblW_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblW_state, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblW_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
            .addGroup(work_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(work_addrLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(work_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_workaddr)
                        .addGroup(work_addrLayout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(work_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblW_streetaddr, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblW_city, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblW_zip, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_w_streetaddr, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_w_city, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_w_zip, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(204, Short.MAX_VALUE)))
        );
        work_addrLayout.setVerticalGroup(
            work_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, work_addrLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(lblW_unit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_w_unit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblW_state)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_w_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblW_phone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_w_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(work_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(work_addrLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbl_workaddr)
                    .addGap(18, 18, 18)
                    .addComponent(lblW_streetaddr)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txt_w_streetaddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(lblW_city)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txt_w_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12)
                    .addComponent(lblW_zip)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txt_w_zip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(35, Short.MAX_VALUE)))
        );

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        lblShoesnum.setText("Shoes Number");

        txt_shoesnum.setAutoscrolls(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(home_addr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(work_addr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFirstname)
                                    .addComponent(lblSsn)
                                    .addComponent(txt_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAge)
                                            .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblLastname))
                                        .addGap(41, 41, 41)
                                        .addComponent(txt_shoesnum, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblShoesnum)
                                        .addGap(58, 58, 58))))
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnBack))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLastname)
                            .addComponent(lblShoesnum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_shoesnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(lblAge)
                        .addGap(7, 7, 7)
                        .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFirstname)
                        .addGap(8, 8, 8)
                        .addComponent(txt_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSsn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_ssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(work_addr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(home_addr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnCreate)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBack, lblTitle});

    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String Firstname = txt_firstname.getText();
        String Lastname = txt_lastname.getText();
        String Ssn = txt_ssn.getText();
        byte Age;
        double Shoesnum;
        
        String H_streetaddr = txt_h_streetaddr.getText();
        int H_unitnum;
        String H_city = txt_h_city.getText();
        String H_state = txt_h_state.getText();
        String H_zipcode = txt_h_zip.getText();
        long H_phonenum;
        
        String W_streetaddr = txt_w_streetaddr.getText();
        int W_unitnum;
        String W_city = txt_w_city.getText();
        String W_state = txt_w_state.getText();
        String W_zipcode = txt_w_zip.getText();
        long W_phonenum;
        
        if (Firstname.isBlank() || Lastname.isBlank() || Ssn.isBlank() || H_streetaddr.isBlank() || H_city.isBlank() || H_state.isBlank() || W_streetaddr.isBlank() || W_city.isBlank() || W_state.isBlank() || W_zipcode.isBlank() || H_zipcode.isBlank()) {
            JOptionPane.showMessageDialog(this, "All fields are mandatory.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            Age = Byte.parseByte(txt_age.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the age input.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            H_unitnum = Integer.parseInt(txt_h_unit.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the home unit number input.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        try {
            W_unitnum = Integer.parseInt(txt_w_unit.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the work unit number input.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            H_phonenum = Long.parseLong(txt_h_phone.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the home phone number input.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        try {
            W_phonenum = Long.parseLong(txt_w_phone.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the work phone number input.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            Shoesnum = Double.parseDouble(txt_shoesnum.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the shoes number input.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Person p = personDirectory.addPerson();
        
        p.setFirstName(Firstname);
        p.setLastName(Lastname);
        p.setSsn(Ssn);
        p.setAge(Age);
        p.setShoesnum(Shoesnum);
        p.setH_streetaddr(H_streetaddr);
        p.setH_unitnum(H_unitnum);
        p.setH_city(H_city);
        p.setH_state(H_state);
        p.setH_zipcode(H_zipcode);
        p.setH_phonenum(H_phonenum);
        p.setW_streetaddr(W_streetaddr);
        p.setW_unitnum(W_unitnum);
        p.setW_city(W_city);
        p.setW_state(W_state);
        p.setW_zipcode(W_zipcode);
        p.setW_phonenum(W_phonenum);
        
        JOptionPane.showMessageDialog(this, "Person profile successfully created.", "Information", JOptionPane.INFORMATION_MESSAGE);
        
        
        txt_firstname.setText("");
        txt_lastname.setText("");
        txt_ssn.setText("");
        txt_age.setText("");
        txt_shoesnum.setText("");
        txt_h_streetaddr.setText("");
        txt_h_unit.setText("");
        txt_h_city.setText("");
        txt_h_state.setText("");
        txt_h_zip.setText("");
        txt_h_phone.setText("");
        txt_w_streetaddr.setText("");
        txt_w_unit.setText("");
        txt_w_city.setText("");
        txt_w_state.setText("");
        txt_w_zip.setText("");
        txt_w_phone.setText("");
        
    }//GEN-LAST:event_btnCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JPanel home_addr;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblH_city;
    private javax.swing.JLabel lblH_phone;
    private javax.swing.JLabel lblH_state;
    private javax.swing.JLabel lblH_streetaddr;
    private javax.swing.JLabel lblH_unit;
    private javax.swing.JLabel lblH_zip;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblShoesnum;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblW_city;
    private javax.swing.JLabel lblW_phone;
    private javax.swing.JLabel lblW_state;
    private javax.swing.JLabel lblW_streetaddr;
    private javax.swing.JLabel lblW_unit;
    private javax.swing.JLabel lblW_zip;
    private javax.swing.JLabel lbl_homeaddr;
    private javax.swing.JLabel lbl_workaddr;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_h_city;
    private javax.swing.JTextField txt_h_phone;
    private javax.swing.JTextField txt_h_state;
    private javax.swing.JTextField txt_h_streetaddr;
    private javax.swing.JTextField txt_h_unit;
    private javax.swing.JTextField txt_h_zip;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_shoesnum;
    private javax.swing.JTextField txt_ssn;
    private javax.swing.JTextField txt_w_city;
    private javax.swing.JTextField txt_w_phone;
    private javax.swing.JTextField txt_w_state;
    private javax.swing.JTextField txt_w_streetaddr;
    private javax.swing.JTextField txt_w_unit;
    private javax.swing.JTextField txt_w_zip;
    private javax.swing.JPanel work_addr;
    // End of variables declaration//GEN-END:variables
}
