/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PersonManager;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author jiaye
 */
public class ViewPersonJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private PersonDirectory personDirectory;
    private Person person;
    /**
     * Creates new form ViewPersonJPanel
     */
    public ViewPersonJPanel(JPanel userProcessContainer, PersonDirectory directory, Person person) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.person = person;
        
        refeshTextFields();
        SetViewMode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home_addr = new javax.swing.JPanel();
        lbl_homeaddr = new javax.swing.JLabel();
        lblH_streetaddr = new javax.swing.JLabel();
        txt_h_streetaddr = new javax.swing.JTextField();
        lblH_unit = new javax.swing.JLabel();
        txt_h_unit = new javax.swing.JTextField();
        lblH_city = new javax.swing.JLabel();
        txt_h_city = new javax.swing.JTextField();
        lblH_state = new javax.swing.JLabel();
        txt_h_state = new javax.swing.JTextField();
        lblH_zip = new javax.swing.JLabel();
        txt_h_zip = new javax.swing.JTextField();
        lblH_phone = new javax.swing.JLabel();
        txt_h_phone = new javax.swing.JTextField();
        work_addr = new javax.swing.JPanel();
        lbl_workaddr = new javax.swing.JLabel();
        lblW_streetaddr = new javax.swing.JLabel();
        lblW_unit = new javax.swing.JLabel();
        txt_w_unit = new javax.swing.JTextField();
        txt_w_streetaddr = new javax.swing.JTextField();
        lblW_city = new javax.swing.JLabel();
        lblW_state = new javax.swing.JLabel();
        txt_w_state = new javax.swing.JTextField();
        txt_w_city = new javax.swing.JTextField();
        lblW_zip = new javax.swing.JLabel();
        lblW_phone = new javax.swing.JLabel();
        txt_w_phone = new javax.swing.JTextField();
        txt_w_zip = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblFirstname = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        lblLastname = new javax.swing.JLabel();
        txt_lastname = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txt_age = new javax.swing.JTextField();
        lblSsn = new javax.swing.JLabel();
        txt_ssn = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblShoesnum = new javax.swing.JLabel();
        txt_shoesnum = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));

        home_addr.setBackground(new java.awt.Color(232, 184, 245));

        lbl_homeaddr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_homeaddr.setText("Home Address");

        lblH_streetaddr.setText("Street Address");

        lblH_unit.setText("Unit Number");

        lblH_city.setText("City");

        lblH_state.setText("State");

        lblH_zip.setText("Zip Code");

        lblH_phone.setText("Phone Number");

        javax.swing.GroupLayout home_addrLayout = new javax.swing.GroupLayout(home_addr);
        home_addr.setLayout(home_addrLayout);
        home_addrLayout.setHorizontalGroup(
            home_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_addrLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(home_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_homeaddr)
                    .addGroup(home_addrLayout.createSequentialGroup()
                        .addGroup(home_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_h_zip, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblH_zip, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_h_city, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblH_city, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_h_streetaddr, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblH_streetaddr, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(home_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_h_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblH_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblH_state, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_h_state, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblH_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_h_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        home_addrLayout.setVerticalGroup(
            home_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_addrLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(lbl_homeaddr)
                .addGap(18, 18, 18)
                .addGroup(home_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblH_unit)
                    .addComponent(lblH_streetaddr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(home_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_h_streetaddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_h_unit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(home_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblH_state)
                    .addComponent(lblH_city))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(home_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_h_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_h_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(home_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblH_zip)
                    .addComponent(lblH_phone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(home_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_h_zip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_h_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        work_addr.setBackground(new java.awt.Color(220, 231, 242));

        lbl_workaddr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_workaddr.setText("Work Address");

        lblW_streetaddr.setText("Street Address");

        lblW_unit.setText("Unit Number");

        lblW_city.setText("City");

        lblW_state.setText("State");

        lblW_zip.setText("Zip Code");

        lblW_phone.setText("Phone Number");

        javax.swing.GroupLayout work_addrLayout = new javax.swing.GroupLayout(work_addr);
        work_addr.setLayout(work_addrLayout);
        work_addrLayout.setHorizontalGroup(
            work_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(work_addrLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(work_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_workaddr)
                    .addGroup(work_addrLayout.createSequentialGroup()
                        .addGroup(work_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblW_streetaddr, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblW_city, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblW_zip, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_w_streetaddr, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_w_city, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_w_zip, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(work_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_w_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_w_state, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_w_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblW_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblW_state, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblW_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        work_addrLayout.setVerticalGroup(
            work_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, work_addrLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_workaddr)
                .addGap(18, 18, 18)
                .addGroup(work_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblW_streetaddr)
                    .addComponent(lblW_unit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(work_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_w_streetaddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_w_unit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(work_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblW_city)
                    .addComponent(lblW_state))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(work_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_w_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_w_state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(work_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblW_zip)
                    .addComponent(lblW_phone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(work_addrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_w_zip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_w_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        lblTitle.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("View Person Profile");

        lblFirstname.setText("First Name");

        txt_firstname.setAutoscrolls(false);

        lblLastname.setText("Last Name");

        txt_lastname.setAutoscrolls(false);

        lblAge.setText("Age");

        txt_age.setAutoscrolls(false);

        lblSsn.setText("Social Security Number");

        txt_ssn.setAutoscrolls(false);

        btnBack.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblShoesnum.setText("Shoes Number");

        txt_shoesnum.setAutoscrolls(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(home_addr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(work_addr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSsn)
                            .addComponent(txt_ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFirstname)
                            .addComponent(txt_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAge)
                                    .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(164, 164, 164))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLastname)
                                    .addComponent(txt_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblShoesnum)
                                    .addComponent(txt_shoesnum, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblTitle)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFirstname)
                            .addComponent(lblLastname))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblShoesnum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_shoesnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSsn)
                        .addGap(7, 7, 7)
                        .addComponent(txt_ssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAge)
                        .addGap(7, 7, 7)
                        .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(work_addr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(home_addr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnSave))
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        String Firstname = txt_firstname.getText();
        String Lastname = txt_lastname.getText();
        String Ssn = txt_ssn.getText();
        byte Age;
        double Shoesnum;
        
        String H_streetaddr = txt_h_streetaddr.getText();
        int H_unitnum;
        String H_city = txt_h_city.getText();
        String H_state = txt_h_state.getText();
        String H_zipcode = txt_h_zip.getText();
        long H_phonenum;
        
        String W_streetaddr = txt_w_streetaddr.getText();
        int W_unitnum;
        String W_city = txt_w_city.getText();
        String W_state = txt_w_state.getText();
        String W_zipcode = txt_w_zip.getText();
        long W_phonenum;
        
        if (Firstname.isBlank() || Lastname.isBlank() || Ssn.isBlank() || H_streetaddr.isBlank() || H_city.isBlank() || H_state.isBlank() || W_streetaddr.isBlank() || W_city.isBlank() || W_state.isBlank() || W_zipcode.isBlank() || H_zipcode.isBlank()) {
            JOptionPane.showMessageDialog(this, "All fields are mandatory.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            Age = Byte.parseByte(txt_age.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the age input.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            H_unitnum = Integer.parseInt(txt_h_unit.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the home unit number input.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        try {
            W_unitnum = Integer.parseInt(txt_w_unit.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the work unit number input.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        

        try {
            H_phonenum = Long.parseLong(txt_h_phone.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the work phone number input.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        try {
            W_phonenum = Long.parseLong(txt_w_phone.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the work phone number input.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            Shoesnum = Double.parseDouble(txt_shoesnum.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please check the shoes number input.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        person.setFirstName(Firstname);
        person.setLastName(Lastname);
        person.setSsn(Ssn);
        person.setAge(Age);
        person.setShoesnum(Shoesnum);
        person.setH_streetaddr(H_streetaddr);
        person.setH_unitnum(H_unitnum);
        person.setH_city(H_city);
        person.setH_state(H_state);
        person.setH_zipcode(H_zipcode);
        person.setH_phonenum(H_phonenum);
        
        person.setW_streetaddr(W_streetaddr);
        person.setW_unitnum(W_unitnum);
        person.setW_city(W_city);
        person.setW_state(W_state);
        person.setW_zipcode(W_zipcode);
        person.setW_phonenum(W_phonenum);
        
        JOptionPane.showMessageDialog(null, "Person profile successfully updated.", "Warning", JOptionPane.WARNING_MESSAGE);
             
        SetViewMode();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        SetEditMode();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        
        // This will reach to the previous panel and trigger an update
        Component[] panelStack = userProcessContainer.getComponents();  //we get the list of all panel in the Container
        JPanel lastPanel = (JPanel) panelStack[panelStack.length -1]; 
        ManagePersonsJPanel manageAccountJPanel = (ManagePersonsJPanel) lastPanel;
        manageAccountJPanel.populateTable();
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel home_addr;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblH_city;
    private javax.swing.JLabel lblH_phone;
    private javax.swing.JLabel lblH_state;
    private javax.swing.JLabel lblH_streetaddr;
    private javax.swing.JLabel lblH_unit;
    private javax.swing.JLabel lblH_zip;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblShoesnum;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblW_city;
    private javax.swing.JLabel lblW_phone;
    private javax.swing.JLabel lblW_state;
    private javax.swing.JLabel lblW_streetaddr;
    private javax.swing.JLabel lblW_unit;
    private javax.swing.JLabel lblW_zip;
    private javax.swing.JLabel lbl_homeaddr;
    private javax.swing.JLabel lbl_workaddr;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_h_city;
    private javax.swing.JTextField txt_h_phone;
    private javax.swing.JTextField txt_h_state;
    private javax.swing.JTextField txt_h_streetaddr;
    private javax.swing.JTextField txt_h_unit;
    private javax.swing.JTextField txt_h_zip;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_shoesnum;
    private javax.swing.JTextField txt_ssn;
    private javax.swing.JTextField txt_w_city;
    private javax.swing.JTextField txt_w_phone;
    private javax.swing.JTextField txt_w_state;
    private javax.swing.JTextField txt_w_streetaddr;
    private javax.swing.JTextField txt_w_unit;
    private javax.swing.JTextField txt_w_zip;
    private javax.swing.JPanel work_addr;
    // End of variables declaration//GEN-END:variables

    private void refeshTextFields() {
        txt_firstname.setText(person.getFirstName());
        txt_lastname.setText(person.getLastName());
        txt_ssn.setText(person.getSsn());
        txt_age.setText(Byte.toString(person.getAge()));
        txt_shoesnum.setText(Double.toString(person.getShoesnum()));
        
        txt_h_streetaddr.setText(person.getH_streetaddr());
        txt_h_unit.setText(Integer.toString(person.getH_unitnum()));
        txt_h_city.setText(person.getH_city());
        txt_h_state.setText(person.getH_state());
        txt_h_zip.setText(person.getH_zipcode());
        txt_h_phone.setText(Long.toString(person.getH_phonenum()));
        
        txt_w_streetaddr.setText(person.getW_streetaddr());
        txt_w_unit.setText(Integer.toString(person.getW_unitnum()));
        txt_w_city.setText(person.getW_city());
        txt_w_state.setText(person.getW_state());
        txt_w_zip.setText(person.getW_zipcode());
        txt_w_phone.setText(Long.toString(person.getW_phonenum()));
        
    }
    
    private void SetViewMode() {
        
        txt_firstname.setEnabled(false);
        txt_lastname.setEnabled(false);
        txt_ssn.setEnabled(false);
        txt_age.setEnabled(false);
        txt_shoesnum.setEnabled(false);
        
        txt_h_streetaddr.setEnabled(false);
        txt_h_unit.setEnabled(false);
        txt_h_city.setEnabled(false);
        txt_h_state.setEnabled(false);
        txt_h_zip.setEnabled(false);
        txt_h_phone.setEnabled(false);
        
        txt_w_streetaddr.setEnabled(false);
        txt_w_unit.setEnabled(false);
        txt_w_city.setEnabled(false);
        txt_w_state.setEnabled(false);
        txt_w_zip.setEnabled(false);
        txt_w_phone.setEnabled(false);
        
        
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(true);
    }
    
    private void SetEditMode() {

        txt_firstname.setEnabled(true);
        txt_lastname.setEnabled(true);
        txt_ssn.setEnabled(true);
        txt_age.setEnabled(true);
        txt_shoesnum.setEnabled(true);
        
        txt_h_streetaddr.setEnabled(true);
        txt_h_unit.setEnabled(true);
        txt_h_city.setEnabled(true);
        txt_h_state.setEnabled(true);
        txt_h_zip.setEnabled(true);
        txt_h_phone.setEnabled(true);
        
        txt_w_streetaddr.setEnabled(true);
        txt_w_unit.setEnabled(true);
        txt_w_city.setEnabled(true);
        txt_w_state.setEnabled(true);
        txt_w_zip.setEnabled(true);
        txt_w_phone.setEnabled(true);
        
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }
}
